buildpack:
  host: git.hubteam.com
  organization: HubSpot
  repository: CMSAssetBuildpack
  branch: main

before:
  - description: Copies assets in the src directory to an @hubspot/boilerplate directory
    commands:
      - mkdir -p @hubspot/boilerplate
      - cp -rv src/. @hubspot/boilerplate
